# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maoda\OneDrive\Escritorio\proyecto final\ui_files\login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 361, 261))
        self.listWidget.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.listWidget.setObjectName("listWidget")
        self.txt_usuario = QtWidgets.QLineEdit(Dialog)
        self.txt_usuario.setGeometry(QtCore.QRect(210, 70, 113, 22))
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_password = QtWidgets.QLineEdit(Dialog)
        self.txt_password.setGeometry(QtCore.QRect(210, 110, 113, 22))
        self.txt_password.setObjectName("txt_password")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 70, 55, 16))
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label.setObjectName("label")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(230, 180, 93, 28))
        self.btn_login.setObjectName("btn_login")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "NOMBRE"))
        self.btn_login.setText(_translate("Dialog", "PushButton"))
